services:
  app:
    build:
      context: .
    image: django_vaddy:latest 
    expose:
      - 8000
    restart: always
    volumes:
      - static:/static
      - sqllite_db:/app/db
    
  web:
    build: ./web
    image: web_vaddy:latest 
    volumes:
      - static:/static #this is to make sure /static requests are routed to the shared volumne on host machine where django static files are stored
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always

volumes:
  static:
  sqllite_db: