name: Destroy Infrastructure

on:
  push:
    branches: [main]  # O el branch que desees

permissions:
  contents: read
  actions: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      - name: Download Terraform State from S3
        env:
          BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          KEY: "path/to/terraform.tfstate"  # Cambia esto a la ruta de tu estado en S3
        run: |
          aws s3 cp s3://$BUCKET_NAME/$KEY terraform.tfstate

      - name: Initialize Terraform
        run: |
          terraform init

      - name: Destroy Terraform Resources
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ secrets.AWS_REGION }}
        run: |
          terraform destroy -auto-approve