name: Deploy to LocalStack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: >-
          --env SERVICES=s3,ecs,iam,logs
          --volume /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-django-image .

      - name: Set up Terraform
        run: |
          curl -LO https://raw.githubusercontent.com/terraform-linters/tflint/master/install.sh
          bash install.sh

      - name: Init Terraform
        run: |
          cd terraform
          terraform init

      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve