name: Deploy_app

on:
  push:
    branches: [develop]
#on:
#  workflow_run:
#    workflows: ["Deploy_infra"]
#    types:
#      - completed  # Se activará cuando el primer workflow haya terminado

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Log in to AWS ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build and push Docker image
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ECR_REPOSITORY_NAME: ${{ secrets.AWS_ECR_REPOSITORY_NAME }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        cd project
        docker-compose build
        echo "ECR Repository Name: $AWS_ECR_REPOSITORY_NAME"
        docker tag $AWS_ECR_REPOSITORY_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_ECR_REPOSITORY_NAME:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_ECR_REPOSITORY_NAME:latest

    - name: Run Docker Compose
      run: docker-compose up -d
      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Elastic IP Artifact
        uses: actions/download-artifact@v4
        with:
          name: elastic-ip

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ECR_REPOSITORY_NAME: ${{ secrets.AWS_ECR_REPOSITORY_NAME }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          #Leer IP
          IP=$(cat eip.txt)
          echo "${IP}"
          # Conectar a la instancia EC2 y ejecutar comandos
          ssh -o StrictHostKeyChecking=no -i /stack1/deploy.pem ubuntu@$EIP << 'EOF'
            # Pull de la última imagen desde ECR
            docker pull $AWS_ACCOUNT_ID..dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_ECR_REPOSITORY_NAME:latest
            # Ejecutar el contenedor
            docker-compose up -d
          EOF